Update to not use static client for operations on devices and provisioning profiles.
Notes:
- There are still many code paths which use the static instance of client, but we are not currently using those code paths.  I have left those unchanged to minimize the chance for conflicts when we merge updates.
- When new methods are used which try to use the static client, we will see errors like:
    "NoMethodError: undefined method `XYZ' for {}:Hash"
  This will happen because we are setting an empty hash as the static client so validation checks will pass.  When we see these, we need to update to pass in the client rather than using the static one similar to what is being done in this PR